title: FOnline Engine
description: Flexible cross-platform isometric game engine
email: cvet@tut.by
theme: jekyll-theme-slate
google_analytics: UA-77340151-2
exclude:
  - BuildTools/
  - Resources/
  - Source/
  - ThirdParty/
